name: Sync Fork

on:
  schedule:
    - cron: "* * * * *" # every hour
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: nocodb
          token: ${{ secrets.PERSONAL_TOKEN }}
          base: master
          head: master
